# Generated by Django 4.2.1 on 2023-05-28 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('groupname', models.CharField(max_length=50)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('news_category_wait', models.BooleanField(default=False)),
                ('worldnews_category_wait', models.BooleanField(default=False)),
                ('images', models.IntegerField(default=0)),
                ('text_requests', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Private_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chat_id', models.CharField(max_length=100)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('in_specialmode', models.BooleanField(default=False)),
                ('news_category_wait', models.BooleanField(default=False)),
                ('worldnews_category_wait', models.BooleanField(default=False)),
                ('images', models.IntegerField(default=0)),
                ('text_requests', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Special_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_wait', models.BooleanField(default=False)),
                ('description_wait', models.BooleanField(default=False)),
                ('chapters_wait', models.BooleanField(default=False)),
                ('subtopics_wait', models.BooleanField(default=False)),
                ('subtopics', models.CharField(max_length=500)),
                ('words_count', models.CharField(max_length=500)),
                ('choice_wait', models.BooleanField(default=False)),
                ('subtopicsList_wait', models.BooleanField(default=False)),
                ('words_count_wait', models.BooleanField(default=False)),
                ('response_type_wait', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('chat', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_chat', to='RapidAI.private_chat')),
            ],
        ),
        migrations.CreateModel(
            name='Wmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=60)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('is_reaction', models.BooleanField()),
                ('sender', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('quoted_message', models.CharField(blank=True, max_length=60, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RapidAI.private_chat')),
                ('groupchat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RapidAI.group')),
                ('special_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RapidAI.special_chat')),
            ],
        ),
    ]
